[phases.setup]
aptPkgs = ["ffmpeg", "libsndfile1", "wget", "lilypond", "musescore", "xvfb"]

[phases.build]
cmds = ["pip install --no-cache-dir setuptools<82 && pip install --no-cache-dir -r requirements.txt"]
